version: "3.9"
services:
    db:
        container_name: users-api-database
        image: "mcr.microsoft.com/mssql/server"
        environment:
            MSSQL_SA_PASSWORD: "DockerSql2021!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports:
          - "1433:1433"

    users-api:
        container_name: users-api
        environment:
          ASPNETCORE_ENVIRONMENT: "Production"
        build: .
        ports:
          - "5000:5000"
        depends_on:
          - db
    